# Generated by Django 4.1.5 on 2023-02-02 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='время создание')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='время обновления')),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True, verbose_name='время удаления')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('form', models.CharField(max_length=200, verbose_name='форма')),
                ('color', models.CharField(choices=[('Red', 'Красная'), ('Black', 'Черная'), ('Green', 'Зеленая'), ('Violet', 'Фиолетовая')], default='Unkown_type', max_length=80, verbose_name='цвет')),
            ],
            options={
                'verbose_name': 'ручка',
                'verbose_name_plural': 'ручки',
                'ordering': ('-color',),
            },
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_of_pen', models.IntegerField(verbose_name='количество')),
                ('number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company.pen', verbose_name='ручка')),
            ],
            options={
                'verbose_name': 'штука',
                'verbose_name_plural': 'штуки',
                'ordering': ('number',),
            },
        ),
    ]
